services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apimaster
      - apislave
    ports:
      - "9999:80"
    networks:
      - backend
    deploy: 
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  apimaster:
    build: .
    networks:
      - backend
      - payment-processor
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/postgres
      SECRET_KEY_BASE: 2IFoUO1y3YPq2m3OMhlsWIWuugFEB7UYvlt+sLLHokLly4kGGmtw4VcbzBK/sU7+
      DEFAULT_SERVICE_URL: http://payment-processor-default:8080
      FALLBACK_SERVICE_URL: http://payment-processor-fallback:8080
      PHX_HOST: "localhost"
      RELEASE_NODE: payment_backend@apimaster
      RELEASE_COOKIE: "RELEASE_COOKIE"
      POOL_SIZE: 40
    ports:
      - 4000:4000
    depends_on:
      - db
    deploy: 
      resources:
        limits:
          cpus: "0.45"
          memory: "115MB"

  apislave:
    image: harddyz/payment_backend
    networks:
      - backend
      - payment-processor
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/postgres
      SECRET_KEY_BASE: 2IFoUO1y3YPq2m3OMhlsWIWuugFEB7UYvlt+sLLHokLly4kGGmtw4VcbzBK/sU7+
      DEFAULT_SERVICE_URL: http://payment-processor-default:8080
      FALLBACK_SERVICE_URL: http://payment-processor-fallback:8080
      PHX_HOST: "localhost"
      RELEASE_NODE: payment_backend@apislave
      RELEASE_COOKIE: "RELEASE_COOKIE"
      POOL_SIZE: 40
    ports:
      - 4001:4000
    depends_on:
      - db
    deploy: 
      resources:
        limits:
          cpus: "0.45"
          memory: "115MB"

  db:
    build: .
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true
