services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apimaster
      - apislave
    ports:
      - "80:80"
    networks:
      - backend
      - payment-processor
    deploy: 
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  apimaster:
    build: .
    networks:
      - backend
      - payment-processor
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/payment_backend_dev
      SECRET_KEY_BASE: 2IFoUO1y3YPq2m3OMhlsWIWuugFEB7UYvlt+sLLHokLly4kGGmtw4VcbzBK/sU7+
      DEFAULT_SERVICE_URL: http://payment-processor-default:8080
      FALLBACK_SERVICE_URL: http://payment-processor-fallback:8080
      PHX_HOST: "localhost"
      RELEASE_NODE: payment_backend@apimaster
      RELEASE_COOKIE: "RELEASE_COOKIE"
    ports:
      - 4000:4000
    depends_on:
      - db
    deploy: 
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"

  apislave:
    build: .
    networks:
      - backend
      - payment-processor
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/payment_backend_dev
      SECRET_KEY_BASE: 2IFoUO1y3YPq2m3OMhlsWIWuugFEB7UYvlt+sLLHokLly4kGGmtw4VcbzBK/sU7+
      DEFAULT_SERVICE_URL: http://payment-processor-default:8080
      FALLBACK_SERVICE_URL: http://payment-processor-fallback:8080
      PHX_HOST: "localhost"
      RELEASE_NODE: payment_backend@apislave
      RELEASE_COOKIE: "RELEASE_COOKIE"
    ports:
      - 4001:4001
    depends_on:
      - db
    deploy: 
      resources:
        limits:
          cpus: "0.35"
          memory: "120MB"

  db:
    image: postgres:17.0
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true
